export const curves = {
  DGC: [
    "_Dot_Gain_Pantone.dgc",
    "_Minimas HD.dgc",
    "Afix_Markandy_C.dgc",
    "Afix_Markandy_K.dgc",
    "Afix_Markandy_M.dgc",
    "Afix_Markandy_Y.dgc",
    "AGB Curva Papel Dupont EPR 2017.dgc",
    "amarelo madel.dgc",
    "Brazicolor_TVI_174Lpi_170_EPR_EXT_Cyan_Preto.dgc",
    "Brazicolor_TVI_174Lpi_170_EPR_EXT_Magenta_Amarelo.dgc",
    "cyan madel.dgc",
    "Degrafica_TVI_174Lpi_114_EXT.dgc",
    "Dot_Gain_Pantone.dgc",
    "DuPont_EPR45_114_V23s_F10min_bump2.dgc",
    "DuPont_EPR45_114_V23s_F10min_bump3.dgc",
    "EG_example_groovy_curve.dgc",
    "EG_FIQ1hto1bump.dgc",
    "EG_FIQ2hto1bump.dgc",
    "EG_FIQ2to1bump.dgc",
    "EG_FIQ3hto1bump.dgc",
    "EG_FIQ3to1bump.dgc",
    "EG_FIQ4hto1bump.dgc",
    "EG_FIQ4to1bump.dgc",
    "EG_FIQ5hto1bump.dgc",
    "EG_FIQ5to1bump.dgc",
    "EG_FIQ6hto1bump.dgc",
    "EG_FIQ6to1bump.dgc",
    "EG_FIQ7hto1bump.dgc",
    "EG_FIQ7to1bump.dgc",
    "EG_FIQ8hto1bump.dgc",
    "EG_FIQ8to1bump.dgc",
    "EG_FIQ10to1bump.dgc",
    "EG_FIQ11to1bump.dgc",
    "EG_FIQ12to1bump.dgc",
    "EG_FIQ14to1bump.dgc",
    "EG_ICPro_minus_5.dgc",
    "EG_ICPro_minus_7.dgc",
    "EG_ICPro_minus_10.dgc",
    "EG_ICPro_plus_5.dgc",
    "EG_ICPro_plus_7.dgc",
    "EG_ICPro_quartertone_minus_6.dgc",
    "EG_narrowweb_ref_numbers.dgc",
    "EG_real_run1.dgc",
    "EG_real_run2.dgc",
    "EG_real_run3.dgc",
    "EG_real_run4.dgc",
    "EG_ref_actual_numbers.dgc",
    "EG_sambaflex_high.dgc",
    "EG_sambaflex_low.dgc",
    "EG_sambaflex_med.dgc",
    "Em Casa FullHD EPR.dgc",
    "example.dgc",
    "FlexCor Girando Sol Dupont EPR 2017.dgc",
    "FTD_H34_Bu10.dgc",
    "HDFlexo.dgc",
    "hp3500gl_c.dgc",
    "hp3500gl_k.dgc",
    "hp3500gl_m.dgc",
    "hp3500gl_y.dgc",
    "hp3500mat_c.dgc",
    "hp3500mat_k.dgc",
    "hp3500mat_m.dgc",
    "hp3500mat_y.dgc",
    "hp3500sm_c.dgc",
    "hp3500sm_k.dgc",
    "hp3500sm_m.dgc",
    "hp3500sm_y.dgc",
    "hpdj_l_cmy.dgc",
    "hpdj_l_k.dgc",
    "hpdj_m_cmy.dgc",
    "hpdj_m_k.dgc",
    "hpdj_r41_cmy.dgc",
    "hpdj_r41_k.dgc",
    "hpdj_r53_cmy.dgc",
    "hpdj_r53_k.dgc",
    "hpdj_r71_cmy.dgc",
    "hpdj_r71_k.dgc",
    "KodakNX_1.dgc",
    "KodakNX_2.dgc",
    "KodakNX_E-45.dgc",
    "MADELPRINT_EXT_44LPC_AMARELO E PRETO.dgc",
    "MADELPRINT_EXT_44LPC_CYAN.dgc",
    "MADELPRINT_EXT_44LPC_MAGENTA.dgc",
    "magenta madel.dgc",
    "midtone_minus_5.dgc",
    "midtone_plus_5.dgc",
    "Minimas HD.dgc",
    "None.dgc",
    "PackMaster_Anilox_140L_no_Cyan.dgc",
    "PackMaster_Anilox_280L_no_Cyan.dgc",
    "Pierplast Flexotech CMYK PEpig ISOC.dgc",
    "Pierplast_Flexotech_PEint_-M_HD.dgc",
    "PItalia_Comexi_PE_PIG_TRANSP_EXT_112LPI_AMARELO.dgc",
    "PItalia_Comexi_PE_PIG_TRANSP_EXT_112LPI_CYAN.dgc",
    "PItalia_Comexi_PE_PIG_TRANSP_EXT_112LPI_MAGENTA.dgc",
    "PItalia_Comexi_PE_PIG_TRANSP_EXT_112LPI_Pantones.dgc",
    "PItalia_Comexi_PE_PIG_TRANSP_EXT_112LPI_PRETO.dgc",
    "PItalia_Curva_Generica_Comexi_Suave.dgc",
    "PItalia_Feva_PE_PIG_TRANSP_EXT_112LPI_AMARELO.dgc",
    "PItalia_Feva_PE_PIG_TRANSP_EXT_112LPI_CYAN.dgc",
    "PItalia_Feva_PE_PIG_TRANSP_EXT_112LPI_MAGENTA.dgc",
    "PItalia_Feva_PE_PIG_TRANSP_EXT_112LPI_PRETO.dgc",
    "Plastimarau_PE_44_Suave_CMYK_2018.dgc",
    "PLASTIMARAU_PE_TRANSP_INTERNO_44LPC_AMARELO.dgc",
    "PLASTIMARAU_PE_TRANSP_INTERNO_44LPC_CYAN.dgc",
    "PLASTIMARAU_PE_TRANSP_INTERNO_44LPC_MAGENTA.dgc",
    "PLASTIMARAU_PE_TRANSP_INTERNO_44LPC_PANTONE.dgc",
    "PLASTIMARAU_PE_TRANSP_INTERNO_44LPC_PANTONE2.dgc",
    "PLASTIMARAU_PE_TRANSP_INTERNO_44LPC_PRETO.dgc",
    "preto madel.dgc",
    "Romulo - Fotolito para Flat - Poliquimica.dgc",
    "Star_Print_FIT_Couche_Bopp_114_EXT_149LPI_AMARELO.dgc",
    "Star_Print_FIT_Couche_Bopp_114_EXT_149LPI_CYAN.dgc",
    "Star_Print_FIT_Couche_Bopp_114_EXT_149LPI_MAGENTA.dgc",
    "Star_Print_FIT_Couche_Bopp_114_EXT_149LPI_PRETO.dgc",
    "Star_Print_FIT_Couche_Bopp_170_EXT_149LPI_AMARELO.dgc",
    "Star_Print_FIT_Couche_Bopp_170_EXT_149LPI_CYAN.dgc",
    "Star_Print_FIT_Couche_Bopp_170_EXT_149LPI_MAGENTA.dgc",
    "Star_Print_FIT_Couche_Bopp_170_EXT_149LPI_PRETO.dgc",
    "Zeta_1.14_Dupont_EPR.dgc",
  ],
  ICPRO: [
    "Afix_Markandy.icpro",
    "AGB Curva Papel Dupont EPR 2017.icpro",
    "Brazicolor_TVI_174Lpi_170_EPR_EXT.icpro",
    "CUSTOMER_INFO_1.icpro",
    "CUSTOMER_INFO_2.icpro",
    "CUSTOMER_INFO_3.icpro",
    "CUSTOMER_INFO_4.icpro",
    "CUSTOMER_INFO_5.icpro",
    "Degrafica_TVI_174Lpi_114_EXT.icpro",
    "Dot_Gain_Pantone.icpro",
    "Dupont_EPR.icpro",
    "dupont114_DPR_V9seg_F3min.icpro",
    "dupont114_V8seg_F5min.icpro",
    "E-45.icpro",
    "EG_DFH_Bumps.icpro",
    "EG_DPI_Bumps.icpro",
    "HDFlexo.icpro",
    "KodakNX.icpro",
    "Madelprint Mimo (Curva da PItalia para Madel).icpro",
    "MADELPRINT_EXT_44LPC_DupontEPR.icpro",
    "Packmaster_Dupont_EPR.icpro",
    "PCW_Acetech Comexi Bopp Fosco ESXR.icpro",
    "PCW_Acetech Comexi PE Pig ESXR.icpro",
    "PCW_Acetech Comexi PE Pig Geladeira ESXR.icpro",
    "PCW_Acetech Comexi PE Trans ESXR.icpro",
    "PCW_Acetech Comexi PE Trans Externo ESXR.icpro",
    "PCW_Acetech Comexi PET ESXR.icpro",
    "PCW_Acetech Comexi PET Externo ESXR.icpro",
    "PCW_Arte Solucoes Modular Bopp 68lpcm.icpro",
    "PCW_C4 WSI.icpro",
    "PCW_C9 WSI.icpro",
    "PCW_C12 WSI.icpro",
    "PCW_C16 0,6mm.icpro",
    "PCW_C30 WSI.icpro",
    "PCW_Crystal C9 175lpi.icpro",
    "PCW_Crystal V C16-9.icpro",
    "PCW_E46_C16.icpro",
    "PCW_E50_C16.icpro",
    "PCW_Emcasa Comexi Bopp Trans 44 lpcm.icpro",
    "PCW_Emcasa Comexi Bopp Trans 64 lpcm.icpro",
    "PCW_EmCasa ECG Comexi PP 2022 ESXR.icpro",
    "PCW_Etikor Markandy P7 Bopp 69lpcm.icpro",
    "PCW_Etikor Markandy P7 Bopp 74lpcm ESXR.icpro",
    "PCW_Etikor Markandy P7 Bopp 74lpcm NX.icpro",
    "PCW_EtiqEcia Etirama FIT Bopp Fosco NX.icpro",
    "PCW_EtiqEcia Etirama FIT Bopp Fosco V Brilho NX.icpro",
    "PCW_EtiqEcia Etirama FIT Bopp Perola V Fosco NX.icpro",
    "PCW_EtiqEcia Etirama FIT Bopp Perola Verniz NX FLINT.icpro",
    "PCW_EtiqEcia Etirama FIT Bopp Perola Verniz NX.icpro",
    "PCW_EtiqEcia Etirama FIT Bopp Trans NX.icpro",
    "PCW_EtiqEcia Etirama FIT Bopp Trans NX_(2).icpro",
    "PCW_EtiqEcia Etirama FIT Couche V Brilho NX.icpro",
    "PCW_EtiqEcia Etirama FIT Metal V Brilho NX.icpro",
    "PCW_EtiqEcia Etirama FIT Metal V Fosco NX.icpro",
    "PCW_EtiqEcia Etirama Wine Bopp Verniz NX.icpro",
    "PCW_EtiqEcia Etirama Wine Couche Verniz NX.icpro",
    "PCW_Flexcor Etirama Bopp 60lpc.icpro",
    "PCW_Flexcor Etirama Papel 60lpc.icpro",
    "PCW_Flexcor M6 Kromia ESR.icpro",
    "PCW_Flexul Nilpeter FB 350S Bopp NX.icpro",
    "PCW_Flexul Nilpeter FB 350S Bopp Trans NX.icpro",
    "PCW_Flexul Nilpeter FB 350S Metal NX.icpro",
    "PCW_G54_C16.icpro",
    "PCW_Guara Comexi PE Pig 64 lpcm.icpro",
    "PCW_Guara Comexi PE Trans 64 lpcm.icpro",
    "PCW_Guara Comexi PP 64 lpcm.icpro",
    "PCW_Guara Etirama Metal ESXR.icpro",
    "PCW_Guara Etirama Metal NX.icpro",
    "PCW_Inplac 8GL01 PE Pig.icpro",
    "PCW_Inplac 8GL01 PE Trans.icpro",
    "PCW_Inplac 8GL01 PET.icpro",
    "PCW_Inplac 8GL01 PP Fosco.icpro",
    "PCW_Master Print Nilpeter 250 Bopp Perola ESXR 2023.icpro",
    "PCW_Master Print Nilpeter 250 Bopp Trans ESXR 2023.icpro",
    "PCW_Master Print Nilpeter 250 Couche ESXR 2023.icpro",
    "PCW_Master Print Nilpeter 250 Metal ESXR 2023.icpro",
    "PCW_Master Print Nilpeter 350 Bopp Perola ESXR 2023.icpro",
    "PCW_Master Print Nilpeter 350 Bopp Trans ESXR 2023.icpro",
    "PCW_Master Print Nilpeter 350 Couche ESXR 2023.icpro",
    "PCW_Master Print Nilpeter 350 Metal ESXR 2023.icpro",
    "PCW_Master Print Nilpeter 350 Sleeve ESXR 2023.icpro",
    "PCW_Master Print Nilpeter FA 420 Sleeve ESXR 2023.icpro",
    "PCW_MG45.icpro",
    "PCW_Plastimarau Flexotech Bopp Trans Fosco ESXR 2022.icpro",
    "PCW_Plastimarau Flexotech PE Pig ESXR 2022.icpro",
    "PCW_Plastimarau Flexotech PE Pig ESXR FAST 2023.icpro",
    "PCW_Plastimarau Flexotech PE Trans ESXR 2022.icpro",
    "PCW_Plastimarau Flexotech PE Trans Fosco ESXR 2022.icpro",
    "PCW_Plastimarau Flexotech PET ESXR 2022.icpro",
    "PCW_Plastimarau Gama Ex Flexopower Bopp Trans Fosco ESXR 2022.icpro",
    "PCW_Plastimarau Gama Ex Flexopower PE Pig ESXR 2022.icpro",
    "PCW_Plastimarau Gama Ex Flexopower PE Trans ESXR 2022.icpro",
    "PCW_Plastimarau Gama Ex Flexopower PE Trans Fosco ESXR 2022.icpro",
    "PCW_Plastimarau Gama Ex Flexopower PET ESXR 2022.icpro",
    "PCW_Plastimarau Gama Ex Flexopower PET LFH 2023.icpro",
    "PCW_Plastimarau Gama Ex Flexopower PET LFH 2023_(2).icpro",
    "PCW_Plastmarau Flexotech PE Trans 64 lpcm relatorio.icpro",
    "PCW_Plastmarau Flexotech PET 64 lpcm relatorio.icpro",
    "PCW_Plastmarau Flexotech PET 80lpcm.icpro",
    "PCW_Plastmarau Flexotech PET 80lpcm_BASE CMYK.icpro",
    "PCW_Plastmarau Flexotech PP 44 lpc.icpro",
    "PCW_Plaszom Flexopower Bopp ESXR.icpro",
    "PCW_Plaszom Flexopower Bopp ESXR_ANSI A.icpro",
    "PCW_Plaszom Flexopower Bopp ESXR_Nova Leitura.icpro",
    "PCW_Plaszom Flexopower PE ESXR.icpro",
    "PCW_Plaszom Flexopower PE ESXR_Nova Leitura.icpro",
    "PCW_Relatorio Grafica Marx Couche.icpro",
    "PCW_Relatorio Grafica Marx Metal.icpro",
    "PCW_Relatorio PCR Label.icpro",
    "PCW_Relatorio Serviplas Comexi F3 PE Trans ESXR.icpro",
    "PCW_Relatorio Serviplas Comexi F3 PET Trans ESXR.icpro",
    "PCW_Relatorio Serviplas Comexi F3 PP Trans ESXR.icpro",
    "PCW_Somar Flexotech PET.icpro",
    "PCW_Somar Flexotech PP.icpro",
    "PCW_TESTE CRYSTAL V WSi.icpro",
    "PCW_TESTE ETIQUECIA.icpro",
    "PCW_TESTE FULL FM.icpro",
    "PItalia_Comexi_Curva PE_Pig_Trans_DupontEPR.icpro",
    "PItalia_Feva_Curva PE_Pig_Trans_DupontEPR.icpro",
    "PMarau Curva PE_Trans_DupontEPR.icpro",
    "Star_Print_FIT_Couche_Bopp_114_EXT_149LPI.icpro",
    "Star_Print_FIT_Couche_Bopp_170_EXT_149LPI.icpro",
    "Teste_Gama expan.icpro",
  ],
  PRSYNC: [
    "Acplast FlexoTech PE Trans.prsync",
    "Adeprint_Kromia_WinFlexo.prsync",
    "All Print MaqPress 160.prsync",
    "ArtPress.prsync",
    "aUTOMACAO_SVERNIZ.prsync",
    "Automacao_Verniz.prsync",
    "Benevenuti Betaflex 160.prsync",
    "Benevenuti Kromia 250.prsync",
    "Benevenuti Reinaflex 250.prsync",
    "BobPack.prsync",
    "E-33.prsync",
    "E-35.prsync",
    "E-37.prsync",
    "E-40.prsync",
    "E-40_B2.prsync",
    "E-40_B4.prsync",
    "E-45.prsync",
    "E-45_Automacao.prsync",
    "E-50.prsync",
    "EmCasa.prsync",
    "EmCasa_G34.prsync",
    "EmCasa_G34_B4.prsync",
    "F-45.prsync",
    "Flexcor ESXR - M4 - BOPP - E50.prsync",
    "Flexcor ESXR - M4 - BOPP - G54.prsync",
    "Flexcor ESXR - M4 - TRANS - E46.prsync",
    "Flexcor ESXR - M4 - TRANS - E50.prsync",
    "Flexcor ESXR - M4 - TRANS - G54.prsync",
    "Flexcor Kromia M6 Sleeve NX - Relatorio.prsync",
    "FlexCor M5 Etirama 350 Bopp.prsync",
    "FlexCor M5 Etirama 350 Papel.prsync",
    "Flexcor TC4 PVC.prsync",
    "Flexul Etirama Mod 021 Bopp.prsync",
    "Flexul Etirama Mod 021 Metal.prsync",
    "Flexul Etirama Mod 021 Papel.prsync",
    "Flexul Etirama Mod 037 Bopp.prsync",
    "Flexul Etirama Mod 037 Metal.prsync",
    "Flexul Etirama Mod 037 Papel.prsync",
    "Fogra - ISO 12647-2 - First 5 - Agua - Bopp.prsync",
    "Fogra - ISO 12647-2 - First 5 - Agua - Papel.prsync",
    "Fogra - ISO 12647-2 - First 5 - Solvente - Filme.prsync",
    "Fogra - ISO 12647-2 - First 5 - Solvente - Papel.prsync",
    "Fogra - ISO 12647-2 - First 5 - UV - Filme.prsync",
    "Fogra - ISO 12647-2 - First 5 - UV - Papel.prsync",
    "Gama Expandida TVI.prsync",
    "Gama Expandida.prsync",
    "Gesa Etirama 350 Bopp.prsync",
    "Gesa Etirama 350 Metal.prsync",
    "Gesa Etirama 350 Papel.prsync",
    "Grafica10 G40_AGB.prsync",
    "H-34_Poliquimica.prsync",
    "ISO 12647-2_C.prsync",
    "Joviva.prsync",
    "labelsul_kromia470.prsync",
    "Labelsul_Nilpeter_Papel_Bopp_Fosco_e_Perola.prsync",
    "Luna Flexo Kromia 350_B2.prsync",
    "MADELPRINT_EXT_44LPC_DupontEPR.prsync",
    "MultiPrint 1.14 EPR ISO C.prsync",
    "Noschang Etirama Fit.prsync",
    "NX-E-40.prsync",
    "NX-E-40_JOVIVA.prsync",
    "NX-E-43.prsync",
    "NX-E-45.prsync",
    "NX-E-45_EtiqEcia.prsync",
    "NX-F-43.prsync",
    "NX-G-35.prsync",
    "NX-G-40.prsync",
    "NX-G-43.prsync",
    "NX-H-40_EtiqEcia.prsync",
    "NX-H-45.prsync",
    "NX-Labelcolor 350.prsync",
    "NX-Labelcolor 450.prsync",
    "NX-Malires-E-45.prsync",
    "PCW_Acetech Comexi Bopp Fosco ESXR_135.prsync",
    "PCW_Acetech Comexi PE Pig ESXR_135.prsync",
    "PCW_Acetech Comexi PE Pig Geladeira ESXR_135.prsync",
    "PCW_Acetech Comexi PE Trans ESXR_135.prsync",
    "PCW_Acetech Comexi PE Trans Externo ESXR_135.prsync",
    "PCW_Acetech Comexi PET ESXR_135.prsync",
    "PCW_Acetech Comexi PET Externo ESXR_135.prsync",
    "PCW_Arte Solucoes Modular Bopp 68lpcm_175.prsync",
    "PCW_BASE GAMA WSI.prsync",
    "PCW_C4 WSI_150.prsync",
    "PCW_C4 WSI_160.prsync",
    "PCW_C9 WSI_160.prsync",
    "PCW_C12 WSI_150.prsync",
    "PCW_C16 0,6mm_150.prsync",
    "PCW_C30 WSI_150.prsync",
    "PCW_Crystal C9 175lpi_150.prsync",
    "PCW_Crystal V C16-9_160.prsync",
    "PCW_E30_2.84_B4.prsync",
    "PCW_E35_C16_C.prsync",
    "PCW_E35_C16_EST.prsync",
    "PCW_E35_P8_C16_C.prsync",
    "PCW_E37_C16_C.prsync",
    "PCW_E37_C16_EST.prsync",
    "PCW_E40_C16_C.prsync",
    "PCW_E40_C16_EST.prsync",
    "PCW_E40_C16_EST_teste.prsync",
    "PCW_E40_JOVIVA_C16_C.prsync",
    "PCW_E40_JOVIVA_C16_EST.prsync",
    "PCW_E40_VIDA_C16_C.prsync",
    "PCW_E40_VIDA_C16_EST.prsync",
    "PCW_E-45_C9_Circular.prsync",
    "PCW_E45_C12_C.prsync",
    "PCW_E45_C12_EST.prsync",
    "PCW_E45_C16_68lpcm_C.prsync",
    "PCW_E45_C16_C.prsync",
    "PCW_E45_C16_EST.prsync",
    "PCW_E46_C16_68lpcm_C.prsync",
    "PCW_E46_C16_C.prsync",
    "PCW_E46_C16_EST.prsync",
    "PCW_E46_Plastmarau_C16_C.prsync",
    "PCW_E46_Plastmarau_C16_EST.prsync",
    "PCW_E-50_C4_C.prsync",
    "PCW_E-50_C9_C.prsync",
    "PCW_E-50_C9_C_59lpcm.prsync",
    "PCW_E50_C16_C.prsync",
    "PCW_E50_C16_EST.prsync",
    "PCW_E56_C16_C.prsync",
    "PCW_E56_C16_EST.prsync",
    "PCW_Emcasa Comexi Bopp Trans 44 lpcm_110.prsync",
    "PCW_Emcasa Comexi Bopp Trans 64 lpcm_160.prsync",
    "PCW_EmCasa ECG Comexi PP 2022 ESXR_160.prsync",
    "PCW_Etikor Markandy P7 Bopp 69lpcm_150.prsync",
    "PCW_Etikor Markandy P7 Bopp 74lpcm ESXR_175.prsync",
    "PCW_Etikor Markandy P7 Bopp 74lpcm NX_175.prsync",
    "PCW_EtiqEcia Etirama FIT Bopp Fosco NX_175.prsync",
    "PCW_EtiqEcia Etirama FIT Bopp Fosco V Brilho NX_175.prsync",
    "PCW_EtiqEcia Etirama FIT Bopp Perola V Fosco NX_175.prsync",
    "PCW_EtiqEcia Etirama FIT Bopp Perola Verniz NX FLINT_175.prsync",
    "PCW_EtiqEcia Etirama FIT Bopp Perola Verniz NX_175.prsync",
    "PCW_EtiqEcia Etirama FIT Bopp Trans NX_150.prsync",
    "PCW_EtiqEcia Etirama FIT Couche V Brilho NX_150.prsync",
    "PCW_EtiqEcia Etirama FIT Metal V Brilho NX_150.prsync",
    "PCW_EtiqEcia Etirama FIT Metal V Fosco NX_150.prsync",
    "PCW_EtiqEcia Etirama Wine Bopp Verniz NX_150.prsync",
    "PCW_EtiqEcia Etirama Wine Couche Verniz NX_150.prsync",
    "PCW_F40_C9_C.prsync",
    "PCW_F40_C16_EST.prsync",
    "PCW_Flexcor Etirama Bopp 60lpc_150.prsync",
    "PCW_Flexcor Etirama Papel 60lpc_150.prsync",
    "PCW_Flexcor M6 Kromia ESR_150.prsync",
    "PCW_Flexul Nilpeter FB 350S Bopp NX_150.prsync",
    "PCW_Flexul Nilpeter FB 350S Bopp Trans NX_150.prsync",
    "PCW_Flexul Nilpeter FB 350S Metal NX_150.prsync",
    "PCW_Flexul-2024_E45_C16_C.prsync",
    "PCW_Flexul-2024_E45_C16_EST.prsync",
    "PCW_G30_C16_EST.prsync",
    "PCW_G35_C9_C.prsync",
    "PCW_G35_C16_C.prsync",
    "PCW_G35_C16_EST.prsync",
    "PCW_G35_C16_IMPERIALLE_EST.prsync",
    "PCW_G35_C19_C.prsync",
    "PCW_G35_C19_EST.prsync",
    "PCW_G35_RAGUIFE_C16_EST.prsync",
    "PCW_G40_C9_C.prsync",
    "PCW_G40_C16_C.prsync",
    "PCW_G40_C16_EST.prsync",
    "PCW_G40_C22_EST.prsync",
    "PCW_G43_C16_EST.prsync",
    "PCW_G45_C16_C.prsync",
    "PCW_G45_C16_EST.prsync",
    "PCW_G50_C16_C.prsync",
    "PCW_G50_C16_EST.prsync",
    "PCW_G54_C16_C.prsync",
    "PCW_G54_C16_EST.prsync",
    "PCW_G56C-54MYK-45P.prsync",
    "PCW_Guara Comexi PE Pig 64 lpcm_160.prsync",
    "PCW_Guara Comexi PE Trans 64 lpcm_160.prsync",
    "PCW_Guara Comexi PP 64 lpcm_160.prsync",
    "PCW_Guara Etirama Metal ESXR_150.prsync",
    "PCW_Guara Etirama Metal NX_150.prsync",
    "PCW_Inplac 8GL01 PE Pig_160.prsync",
    "PCW_Inplac 8GL01 PE Trans_160.prsync",
    "PCW_Inplac 8GL01 PET_160.prsync",
    "PCW_Inplac 8GL01 PP Fosco_160.prsync",
    "PCW_Master Print Nilpeter 250 Bopp Perola ESXR 2023_150.prsync",
    "PCW_Master Print Nilpeter 250 Bopp Trans ESXR 2023_150.prsync",
    "PCW_Master Print Nilpeter 250 Couche ESXR 2023_150.prsync",
    "PCW_Master Print Nilpeter 250 Metal ESXR 2023_150.prsync",
    "PCW_Master Print Nilpeter 350 Bopp Perola ESXR 2023_150.prsync",
    "PCW_Master Print Nilpeter 350 Bopp Trans ESXR 2023_150.prsync",
    "PCW_Master Print Nilpeter 350 Couche ESXR 2023_150.prsync",
    "PCW_Master Print Nilpeter 350 Metal ESXR 2023_150.prsync",
    "PCW_Master Print Nilpeter 350 Sleeve ESXR 2023_150.prsync",
    "PCW_Master Print Nilpeter FA 420 Sleeve ESXR 2023_150.prsync",
    "PCW_MG45_150.prsync",
    "PCW_Plastimarau Flexotech Bopp Trans Fosco ESXR 2022_160.prsync",
    "PCW_Plastimarau Flexotech PE Pig ESXR 2022_160.prsync",
    "PCW_Plastimarau Flexotech PE Pig ESXR FAST 2023_160.prsync",
    "PCW_Plastimarau Flexotech PE Trans ESXR 2022_160.prsync",
    "PCW_Plastimarau Flexotech PE Trans Fosco ESXR 2022_160.prsync",
    "PCW_Plastimarau Flexotech PET ESXR 2022_160.prsync",
    "PCW_Plastimarau Gama Ex Flexopower Bopp Trans Fosco ESXR 2022_160.prsync",
    "PCW_Plastimarau Gama Ex Flexopower PE Pig ESXR 2022_160.prsync",
    "PCW_Plastimarau Gama Ex Flexopower PE Trans ESXR 2022_160.prsync",
    "PCW_Plastimarau Gama Ex Flexopower PE Trans Fosco ESXR 2022_160.prsync",
    "PCW_Plastimarau Gama Ex Flexopower PET ESXR 2022_160.prsync",
    "PCW_Plastimarau Gama Ex Flexopower PET LFH 2023_(2)_160.prsync",
    "PCW_Plastimarau Gama Ex Flexopower PET LFH 2023_160.prsync",
    "PCW_Plastmarau Flexotech PE Trans 64 lpcm relatorio_160.prsync",
    "PCW_Plastmarau Flexotech PET 64 lpcm relatorio_160.prsync",
    "PCW_Plastmarau Flexotech PET 80lpcm_200.prsync",
    "PCW_Plastmarau Flexotech PET 80lpcm_BASE CMYK_200.prsync",
    "PCW_Plastmarau Flexotech PP 44 lpc_120.prsync",
    "PCW_Plaszom Flexopower Bopp ESXR_135.prsync",
    "PCW_Plaszom Flexopower Bopp ESXR_ANSI A_135.prsync",
    "PCW_Plaszom Flexopower Bopp ESXR_Nova Leitura_135.prsync",
    "PCW_Plaszom Flexopower PE ESXR_135.prsync",
    "PCW_Plaszom Flexopower PE ESXR_Nova Leitura_135.prsync",
    "PCW_Pmarau 2023_Fast_PE PIG.prsync",
    "PCW_Relatorio Grafica Marx Couche_150.prsync",
    "PCW_Relatorio Grafica Marx Metal_150.prsync",
    "PCW_Relatorio PCR Label_150.prsync",
    "PCW_Relatorio Serviplas Comexi F3 PE Trans ESXR_160.prsync",
    "PCW_Relatorio Serviplas Comexi F3 PET Trans ESXR_160.prsync",
    "PCW_Relatorio Serviplas Comexi F3 PP Trans ESXR_160.prsync",
    "PCW_Somar Flexotech PET_160.prsync",
    "PCW_Somar Flexotech PP_160.prsync",
    "PCW_TESTE CRYSTAL V WSi_160.prsync",
    "PCW_TESTE ETIQUECIA_150.prsync",
    "PCW_TESTE FULL FM_245.prsync",
    "PerfilGraf G34.prsync",
    "PerfilGraf.prsync",
    "Pierplast Flexotech CMYK PEpig ISOC.prsync",
    "PItalia_Comexi_Generic_2017.prsync",
    "Plastimarau_PE_44_Suave_CMYK_2018_F-37.prsync",
    "Pomerplast.prsync",
    "Ref-ECG-CMYKOGV_FOGRA55_TAC300.prsync",
    "Relatorio EmCasa ECG.prsync",
    "RotaFlexo Etirama FIT UV 250 Bopp.prsync",
    "RotaFlexo Etirama FIT UV 250 Papel.prsync",
    "RotaFlexo Etirama TC agua Papel Cartao.prsync",
    "RotaFlexo Etirama TC agua Papel.prsync",
    "Standard ECG.prsync",
    "teste_emcasa.prsync",
    "Uniplast_Feva_FlexoTech_NewFlex_PEpigtrans.prsync",
    "Uniplast_Feva_NewFlex_PEpig.prsync",
    "Uniplast_Feva_NewFlex_PEtrans.prsync",
    "Uniplast_Flexo_Tech_NewFlex_PEpig.prsync",
    "Uniplast_Flexo_Tech_NewFlex_PEtrans.prsync",
    "WSI0_G34.prsync",
  ],
};
